/** @type {import('tailwindcss').Config} */
const colors = require("tailwindcss/colors");
module.exports = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx,vue}"],
  theme: {
    extend: {},
    colors: {
      lavender: "#EEF1FA",
      snow: "#FFFFFF",
      "purple-heart": "#8676FF",
      dad: "#5A5A89",
      dark: "#9292C1",
      bluedark: "#176BF8",
      birches: "#01F1E3",
      "purple-blue": "#6A6A9F",
      blue: "#023AFF",
      "night-blue": "#383874",
      "electric-green": "#00B929",
      "fervent-pink": "#FF708B",
      "red-orange": "#FFBA69",
      "blueish-black": "#191932",
      slate: colors.slate,
      gray: colors.gray,
      zinc: colors.zinc,
      neutral: colors.neutral,
      stone: colors.stone,
      red: colors.red,
      orange: colors.orange,
      amber: colors.amber,
      yellow: colors.yellow,
      lime: colors.yellow,
      green: colors.green,
      emerald: colors.emerald,
      teal: colors.teal,
      cyan: colors.cyan,
      sky: colors.sky,
      blue: colors.blue,
      indigo: colors.indigo,
      violet: colors.violet,
      purple: colors.purple,
      fuchsia: colors.fuchsia,
      pink: colors.pink,
      rose: colors.rose
    },
    screens: {
      sm: "480px",
      md: "960px",
      slg: "1280px",
      lg: "1440px",
      xl: "1900px",
      "2xl": "2560px",
    },
  },
  plugins: [],
  darkMode: "class",
};
