/** @type {import('tailwindcss').Config} */
const colors = require("tailwindcss/colors");
module.exports = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx,vue}"],
  theme: {
    extend: {},
    colors: {
      lavender: "#EEF1FA",
      snow: "#FFFFFF",
      "purple-heart": "#8676FF",
      dad: "#5A5A89",
      dark: "#9292C1",
      bluedark: "#176BF8",
      birches: "#01F1E3",
      "purple-blue": "#6A6A9F",
      blue: "#023AFF",
      "night-blue": "#383874",
      "electric-green": "#00B929",
      "fervent-pink": "#FF708B",
      "red-orange": "#FFBA69",
      "blueish-black": "#191932",
      purple: "#991BFA",
      red: "#FF2D2E",
      slate: colors.slate,
      black: colors.black,
      white: colors.white,
      gray: colors.gray,
      emerald: colors.emerald,
      indigo: colors.indigo,
      yellow: colors.yellow,
      green: colors.green,
    },
    screens: {
      sm: "480px",
      md: "960px",
      lg: "1440px",
      slg: "1280px",
      xl: "1900px",
      "2xl": "2560px",
    },
  },
  plugins: [],
  darkMode: "class",
};
